### ISSUE TITLE
Fix CI Build Error 

### ISSUE THREAD

**Issue by mrthankyou** [Qiskit/qiskit-textbook#125]
CI builds are currently failing for several PRs. After investigating these CI builds I've seen the same error occurring:

```
Setting environment variables from repository settings
$ export GITHUB_TOKEN=[secure]
0.00s$ source ~/virtualenv/python3.7/bin/activate
$ python --version
Python 3.7.1
$ pip --version
pip 19.0.3 from /home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/pip (python 3.7)
install.1
41.16s$ pip install -r requirements.txt
install.2
15.54s$ pip install -r requirements-dev.txt
install.3
0.87s$ gem install bundler
0.08s$ make install
# Check to see whether bundler is already installed. If not, install it.
if [ hash bundler 2>/dev/null ]; then \
gem install bundler;\
fi
bundle install
/home/travis/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)
	from /home/travis/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
	from /home/travis/.rvm/gems/ruby-2.5.3/bin/bundle:23:in `<main>'
	from /home/travis/.rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `eval'
	from /home/travis/.rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `<main>'
Makefile:14: recipe for target 'install' failed
make: *** [install] Error 1
The command "make install" failed and exited with 2 during .
Your build has been stopped.
```

This should be resolved so that CI builds will pass.

**Comment by mrthankyou** [comment]
I unfortunately don't have Docker currently installed on my computer which prevents me from running Travis CI builds locally. If there is an alternative resource(not Docker) please let me know as I can then debug this further. Otherwise someone else will have to tackle this. :(

**Comment by mrthankyou** [comment]
@delapuente 

Thanks for fixing this issue! I'm now closing this issue as this is resolved and my PRs are now passing the CI builds.
